### ISSUE TITLE
doFunction  and parameter

### ISSUE THREAD

**Issue by Satzende** [M5ez/Core2ez#19]
Hello, I do not have enough C ++ skills to know how to give the DOFUNCTION parameter with. Could someone post an example?

**Comment by ropg** [comment]
There's doFunction calls in the [form example](https://github.com/M5ez/Core2ez/blob/master/examples/General/form/form.ino).

**Comment by ropg** [comment]
Do note that I've changed the README to reflect that there is no active development here. I've since gotten into LVGL, the Light and Versatile Graphics Library, and it's simply lightyears ahead of where this could even be. It can be used from C and from micropython and is just cooler than this ever hope to become.

Sorry. (That said, if this works for you by all means use it. It's just not going to change, I'm guessing...)

**Comment by Satzende** [comment]
Thanks for your answer. Lvgl I also looked at it could only stop running (M5 Core2). Will start another attempt.
